### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 1127** [lunr/mamp-curl-tls#1]
I was so excited to find your solution. However it is failing. When I run it, the output at the end, instead of having TLS-SRP support, mine says:   TLS-SRP support:  no      (--enable-tls-srp)

I can't see any way to turn that on - no matter what I do my SSL is still at OpenSSL/0.9.8zd

Oh, one other difference maybe: I'm one OS version higher: Host setup:       x86_64-apple-darwin14.5.0

Thanks in advance.

**Comment by loveloso** [comment]
Did you find a solution for that? I am having exactly the same issue here. "TLS-SRP support: no", and when I try to execute curl command to a https I get a server saying the server (MAMP) dropped the connection. HTTP however works fine.

**Comment by 1127** [comment]
Sorry @loveloso , I don't remember at all what I was doing or even trying to do then. I've had problems with MAMP for years and one of these days will just move onto doing everything myself manually.

**Comment by loveloso** [comment]
No problem @1127 ! I have upgraded to MAMP 5 and problem is solved now. Thanks!
