### ISSUE TITLE
Step 6

### ISSUE THREAD

**Issue by vdecree** [lunr/mamp-curl-tls#2]
Hi there,

Just trying to get this work. I'm on step 6 and I get the error: `No such file or directory`. Can I check that I should be issuing that command in step 6 from the directory I've just installed into mamp, i.e. the `etc` dir?

**Comment by Ex10Dios** [comment]
Did you finish step 5?
You should download this repository and unzip "ca-bundle.tgz" into "/Applications/MAMP" folder.

**Comment by paulcripps** [comment]
I'm getting the same error:

> $ ./configure --prefix=/Applications/MAMP/Library --with-ssl=/usr/local/Cellar/openssl/1.0.2g --with-ca-path=/Applications/MAMP/etc/openssl/certs --with-ca-bundle=/Applications/MAMP/etc/openssl/certs/ca-bundle.crt
> 
> -bash: ./configure: No such file or directory

Any thought what I've missed? 

@vdecree did you get this to work?

**Comment by madebycaliper** [comment]
For anyone who comes here, your openssl version might be slightly different (for example, I have "1.0.2r") so you need to change the version in the `--with-ssl` argument from "1.0.2g" to whatever is on your machine. If you've installed Open SSL via homebrew, try this and you should see the version or versions on your machine:

`$ cd /usr/local/Cellar/openssl`
`$ ls`

**Comment by scottflodin** [comment]
After completing these steps PHP would throw a segmentation fault when using curl with SSL. The solution on my Mac (OS 10.16.6) was to configure  curl with the flag `--with-darwinssl` instead of using the homebrew OpenSSL library `--with-ssl=/usr/local/Cellar/openssl/1.0.2g`, I found the suggestion here: [https://stackoverflow.com/questions/34914473/how-do-i-enable-curl-ssl-on-mac-os-x](url)

**Comment by loveloso** [comment]
> After completing these steps PHP would throw a segmentation fault when using curl with SSL. The solution on my Mac (OS 10.16.6) was to configure curl with the flag `--with-darwinssl` instead of using the homebrew OpenSSL library `--with-ssl=/usr/local/Cellar/openssl/1.0.2g`, I found the suggestion here: [https://stackoverflow.com/questions/34914473/how-do-i-enable-curl-ssl-on-mac-os-x](url)

Thanks a lot @scottflodin ! That helped solve my problem. At the end of Step 6 I was getting "SSL Support: no".

I changed the command to: 
 `./configure --prefix=/Applications/MAMP/Library --with-darwinssl=/usr/local/Cellar/openssl\@1.1/1.1.1d --with-ca-path=/Applications/MAMP/etc/openssl/certs --with-ca-bundle=/Applications/MAMP/etc/openssl/certs/ca-bundle.crt`

Now it works!!

**Comment by jamesp-teamddm** [comment]
Documentation updated to note how to find the correct path based on what version of OpenSSL is installed by homebrew.
