### ISSUE TITLE
No luck - but here's my solution

### ISSUE THREAD

**Issue by TheGitPanda** [lunr/mamp-curl-tls#4]
First of all thanks jamesp-teamddm for this suggestion. I did try following the steps but got the `File not found in directory` error at Step 6. It didn't appear to have the right folder there.

My solution - it's really simple. But could be an inconvenience to some.

Store the desired part of script (that needs TLS 1.2) in any folder on the Mac. Run `php -S localhost:8000` from Terminal. If you've written your code in a modular way, you can just do all calls to it at this URL.

Example PHP Curl Request (from your main MAMP/ localhost site)
```
$curlSession = curl_init();
curl_setopt($curlSession, CURLOPT_URL, 'http://localhost:8000/'); // Add params here
curl_setopt($curlSession, CURLOPT_BINARYTRANSFER, true);
curl_setopt($curlSession, CURLOPT_RETURNTRANSFER, true);
echo curl_exec($curlSession);
curl_close($curlSession);
```
When you deploy to prod or other envs, just move your files back in. For me, this was the best solution to accept as I just want to get this f'ing project finished PROPERLY ;)

**Comment by jamesp-teamddm** [comment]
Documentation updated to note how to find the correct path based on what version of OpenSSL is installed by homebrew.
