### ISSUE TITLE
Step 6 update the openssl version

### ISSUE THREAD

**Issue by p4trizio** [lunr/mamp-curl-tls#5]
Hi, thank you for the very useful guide.
On step 6 I had to change 
`--with-ssl=/usr/local/Cellar/openssl/1.0.2g `
to 
`--with-ssl=/usr/local/Cellar/openssl/1.0.2l`

Thank you

**Comment by freel132** [comment]
Helped me this to fix my error! THX

**Comment by hamishirving** [comment]
@lunr Thanks for this guide - you're a life saver! 

@p4trizio Thanks, this worked for me too.

**Comment by Ex10Dios** [comment]
On step 6 you should check what is the last version you have installed in /usr/local/Cellar/openssl/ folder and write it to command.
Now "1.0.2m" is available.

**Comment by davisshaver** [comment]
As of today, `1.0.2p`.

**Comment by danganeev** [comment]
I used 1.0.2r. But dude you're a lifesaver! If I hadn't checked out Issues section out of desperation, I would've ended up updating my operation system just so that I could install later MAMP. Luckily, I now don't have to do any of that!

**Comment by craigcri** [comment]
I used 1.0.2t successfully. 

Someone should add a note to the main README to double check your local filename in dir /usr/local/Cellar/openssl/

**Comment by jamesp-teamddm** [comment]
Updated documentation to note latest OpenSSL version with notes on how to find what version homebrew installed.
